{{- if and (.Values.scim.credentials.volume.enabled) (eq .Values.scim.credentials.volume.kind "PersistentVolumeClaim") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ tpl .Values.scim.credentials.volume.claimName . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/application: {{ template "common.names.fullname" . }}
    {{- with .Values.scim.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.scim.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.scim.credentials.volume.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.scim.credentials.volume.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.scim.credentials.volume.storageClass }}
  {{- if (eq "-" .Values.scim.credentials.volume.storageClass) }}
  storageClassName: '""'
  {{- else }}
  storageClassName: "{{ .Values.scim.credentials.volume.storageClass }}"
  {{- end }}
{{- end }}
{{- end }}
