{{- if .Values.scim.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ template "common.names.fullname" . }}
    {{- with .Values.scim.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.scim.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.scim.service.type }}
  selector:
    app: {{ template "common.names.fullname" . }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.scim.httpPort }}
    - name: https
      port: 443
      protocol: TCP
      targetPort: {{ .Values.scim.httpsPort }}
{{- end }}
